### ISSUE TITLE
No member named 'cartesian' in namespace 'boost::geometry::strategy'

### ISSUE THREAD

**Issue by yulinhuyang** [kleunen/boost_geometry_dissolve#4]
when i use  the hpp in boost 1.72,it compling failed. can you give me a suggestion about it. thank you very much

**Comment by JoachimDunkel** [comment]
For anyone else still facing this problem, the version of this ported to [TileMaker](https://github.com/systemed/tilemaker/tree/master) works with Boost 1.66 +
